# Even Fibonacci numbers

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# 
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


x = 1
lista = []
suma =0
for i in range(4000000):
    lista.append(x)
    if x % 2 ==0:
        suma +=x 
    x = x + lista[i-1]
    if x >= 4000000:
        break


print ("\n",suma, "ANSWER")